### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by justinweiss** [toy/sdoc_all#4]
I've been looking at bringing this up to date with Ruby 1.9 and adding support for multiple plugin directories, but I've been getting a bunch of test failures. Do you know about these? I've been slowly trying to get most of them working, but didn't want to spend a whole lot of time on them if you already knew and were working on them.

**Comment by toy** [comment]
My bad :(
After last changes I made I did not update specs, sorry
I try to find time to fix them, but now I don't have much time

**Comment by justinweiss** [comment]
No worries, I'll fix them as I go. Thanks for the awesome project, btw -- it's incredible how easy it was to get our code and dependencies documented!

**Comment by toy** [comment]
I am glad that my effort was useful not only for me :)

**Comment by toy** [comment]
Fixed specs (also for ruby 1.9)
Also why do you have problems with multiple plugin directories? You can write in config.yml something like:
- plugins: ~/.plugins
- plugins: ~/rails/project/vendor/plugins
- plugins: ~/rails/project2/vendor/plugins

Due to absence of versions in plugins, there is no option for
- plugins: ~/rails/*/vendor/plugins
  or
- plugins: [~/.plugins, ~/rails/project/vendor/plugins, ~/rails/project2/vendor/plugins]
  as if there are multiple instances of same plugin (and there will be) — what should be done?

**Comment by justinweiss** [comment]
Oh, cool! I'll have to try that out -- I tried the array syntax and it didn't work, so I assumed it just wasn't supported.

Thanks!

**Comment by toy** [comment]
Don't forget to update gems — both sdoc-all and sdoc changed. Documentation should be rebuilt :)
